<<<<<<< HEAD
name: mental-health-bot
region: blr1
services:
  - name: web
    github:
      repo: Quarkykoala/Manobal
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: gunicorn app:app
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASS
        type: secret
        value: ${db.PASSWORD}
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: defaultdb
      - key: TWILIO_ACCOUNT_SID
        value: AC48e52113db34586361c7651fb1cf43bd
      - key: TWILIO_AUTH_TOKEN
        type: secret
        value: your-actual-token
      - key: TWILIO_WHATSAPP_NUMBER
        value: +14155238886
      - key: GOOGLE_API_KEY
        type: secret
        value: your-actual-key
      - key: FLASK_DEBUG
        value: "False"

databases:
  - engine: MYSQL
    name: db-mysql-blr1-03087
    version: "8"
    production: false
=======
runtime: python39

entrypoint: gunicorn -b :$PORT app:app

env_variables:
  FLASK_ENV: "production"

handlers:
  - url: /.*
    script: auto
    secure: always

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

inbound_services:
  - warmup

env: standard
>>>>>>> 684b464c7 (Initial commit)
