name: mental-health-bot
region: blr1
services:
  - name: web
    github:
      repo: Quarkykoala/Manobal
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: gunicorn app:app
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DB_USER
        value: doadmin
      - key: DB_PASS
        type: secret
        value: AVNS_mWRasgqERtw0wOMvz8S
      - key: DB_HOST
        value: db-mysql-blr1-03087-do-user-18364467-0.h.db.ondigitalocean.com
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: defaultdb
      - key: TWILIO_ACCOUNT_SID
        value: AC48e52113db34586361c7651fb1cf43bd
      - key: TWILIO_AUTH_TOKEN
        type: secret
        value: your-actual-token
      - key: TWILIO_WHATSAPP_NUMBER
        value: +14155238886
      - key: GOOGLE_API_KEY
        type: secret
        value: your-actual-key
      - key: FLASK_DEBUG
        value: "False"

databases:
  - engine: MYSQL
    name: db-mysql-blr1-03087
    version: "8"
    production: false
