name: mental-health-bot
region: blr1
services:
  - name: web
    github:
      repo: yourusername/mental-health-bot
      branch: main
      deploy_on_push: true
    build_command: pip install -r requirements.txt
    run_command: gunicorn app:app
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASS
        value: ${db.PASSWORD}
      - key: DB_NAME
        value: clients
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: TWILIO_ACCOUNT_SID
        value: AC48e52113db34586361c7651fb1cf43bd
      - key: TWILIO_AUTH_TOKEN
        type: secret
        value: your-auth-token
      - key: TWILIO_WHATSAPP_NUMBER
        value: +14155238886
      - key: GOOGLE_API_KEY
        type: secret
        value: your-google-api-key
      - key: FLASK_DEBUG
        value: "False"

databases:
  - engine: MYSQL
    name: db
    version: "8"
