"""Initial migration

Revision ID: 1433e36103f0
Revises: 96337c4e7256
Create Date: 2024-10-11 19:53:06.519719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1433e36103f0'
down_revision = '96337c4e7256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
