"""Added location, department, consent to User; created KeywordStat model

Revision ID: 17d4bcd6f827
Revises: 1433e36103f0
Create Date: 2024-10-16 20:34:29.687520

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17d4bcd6f827'
down_revision = '1433e36103f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keyword_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('consent_given', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('department', sa.String(length=100), nullable=True))
    op.alter_column('user', 'access_code',
               existing_type=mysql.VARCHAR(length=6),
               type_=sa.String(length=8),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'access_code',
               existing_type=sa.String(length=8),
               type_=mysql.VARCHAR(length=6),
               existing_nullable=False)
    op.drop_column('user', 'department')
    op.drop_column('user', 'location')
    op.drop_column('user', 'consent_given')
    op.drop_table('keyword_stat')
    # ### end Alembic commands ###
