"""Add is_authenticated and authentication_time fields to User model

Revision ID: 65929569b49a
Revises: cbfeb31efbc3
Create Date: 2024-10-10 00:41:24.151864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65929569b49a'
down_revision = 'cbfeb31efbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_authenticated', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('authentication_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('authentication_time')
        batch_op.drop_column('is_authenticated')

    # ### end Alembic commands ###
