"""Add consent_given, location, and department to User model

Revision ID: 680fbc3aac8b
Revises: 87f22ce577b1
Create Date: 2024-10-17 00:17:43.653182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '680fbc3aac8b'
down_revision = '87f22ce577b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('keyword_stat')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('phone_number')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('access_code', mysql.VARCHAR(length=8), nullable=False),
    sa.Column('conversation_started', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('last_message_time', mysql.DATETIME(), nullable=True),
    sa.Column('message_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('conversation_history', mysql.TEXT(), nullable=True),
    sa.Column('is_authenticated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('authentication_time', mysql.DATETIME(), nullable=True),
    sa.Column('consent_given', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('phone_number', ['phone_number'], unique=True)

    op.create_table('keyword_stat',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='keyword_stat_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
