"""Initial migration

Revision ID: 87f22ce577b1
Revises: 17d4bcd6f827
Create Date: 2024-10-16 22:48:40.755225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87f22ce577b1'
down_revision = '17d4bcd6f827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
