"""Create user table

Revision ID: 96337c4e7256
Revises: 65929569b49a
Create Date: 2024-10-11 19:46:49.002327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96337c4e7256'
down_revision = '65929569b49a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
